version: 0.2

phases:

  install:
    commands:

      - |
        echo "Enabling swap ===>"
        fallocate -l 8G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
        free -h
        swapon --show
        echo "<================="

      - |
        echo "Checking AWS credentials ===>"
        aws sts get-caller-identity
        aws s3 ls s3://$ARTIFACT_BUCKET
        echo "<============================"

      - |
        echo "Installing base dependencies ===>"
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y curl git libxkbfile-dev time ca-certificates
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' |  tee /etc/apt/sources.list.d/goreleaser.list
        apt-get update
        apt-get install -y nfpm
        echo "<================================"

      - |
        echo "Installing NVM and Node.js ===>"
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install $NODE_VERSION
        nvm use $NODE_VERSION
        nvm install $NODE_VERSION
        nvm use $NODE_VERSION
        node -v
        npm -v
        echo "<=============================="

      - |
        echo "Installing code-server dependencies ===>"
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm use $NODE_VERSION
        npm ci
        echo "<======================================="

  build:
    commands:
  
      - |
        echo Build started on  `date`

        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm use $NODE_VERSION

        export VERSION=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}@$CODEBUILD_SOURCE_VERSION
        export ARTIFACT_NAME=code-server-$VERSION-linux-$ARCH.tar.gz
        echo "Artifact => $ARTIFACT_NAME"

        echo "Build code-server ===>"
        time npm run build
        echo "<====================="

        echo "Build vscode ===>"
        time npm run build:vscode
        echo "<====================="

        echo "Build release package ===>"
        time npm run release
        time npm run release:standalone
        time npm run test:integration
        time npm run package
        echo "<=========================="

  post_build:
    commands:

      - |
        echo "Uploading artifact ===>"
        S3_KEY="$ARTIFACT_PREFIX/$ARTIFACT_NAME"
        echo "Uploading $S3_KEY to S3..."
        aws s3 cp release-packages/$ARTIFACT_NAME s3://$ARTIFACT_BUCKET/$S3_KEY
        echo "<======================="

      - |
        echo "Pruning old artifacts ===>"
        (
          echo "Keeping last $MAX_ARTIFACTS artifacts in s3://$ARTIFACT_BUCKET/$ARTIFACT_PREFIX"

          OBJECTS=$(aws s3api list-objects-v2 \
            --bucket "$ARTIFACT_BUCKET" \
            --prefix "$ARTIFACT_PREFIX" \
          | jq -r '.Contents | sort_by(.LastModified)[] | .Key')

          echo $OBJECTS

          TOTAL_OBJECTS=$(echo "$OBJECTS" | wc -l)
          echo "Total artifacts found: $TOTAL_OBJECTS"

          if (( $TOTAL_OBJECTS > $MAX_ARTIFACTS )); then
            TO_DELETE=$(( $TOTAL_OBJECTS - $MAX_ARTIFACTS ))
            echo "Pruning $TO_DELETE oldest artifacts..."

            echo "$OBJECTS" | head -n $TO_DELETE | awk '{print $1}' | while read -r KEY; do
              echo "Deleting: s3://$ARTIFACT_BUCKET/$KEY"
              aws s3 rm "s3://$ARTIFACT_BUCKET/$KEY"
            done
          else
            echo "No pruning needed."
          fi
        ) || echo "⚠️ Artifact pruning failed"
        echo "<============================"
