name = "cursor-backend"
main = "backend/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cursor-backend"

[env.staging]
name = "cursor-backend-staging"

# Durable Objects for WebSocket
[durable_objects]
bindings = [
  { name = "WEBSOCKET_DO", class_name = "WebSocketDurableObject" }
]

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = [ "WebSocketDurableObject" ]

# KV Storage for API keys and session data
[[kv_namespaces]]
binding = "API_KEYS"
id = "2a705b445979465ca3d65b117b90411a"
preview_id = "2a705b445979465ca3d65b117b90411a"

[[kv_namespaces]]
binding = "FILE_STORAGE_KV"
id = "cae71ccff3df4039996865e01758f53f"
preview_id = "cae71ccff3df4039996865e01758f53f"

[[kv_namespaces]]
binding = "SESSIONS"
id = "cfc6ab0d08e24421bb602b2d96f5b8ac"
preview_id = "cfc6ab0d08e24421bb602b2d96f5b8ac"

# R2 Storage for file storage
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cursor-files"
preview_bucket_name = "cursor-files-preview"

# Environment variables
[vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"