{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  name: {{ template "code-server.serviceAccountName" . }}
{{- end -}}
