# Use the playwright Docker image
FROM mcr.microsoft.com/playwright:bionic

## NOTES
# Somehow get code-server artifact
# Run it locally on port 8080
# so that it can be accessed in our tests

# It should build the project
# Start code server and then we should run the tests