#!/bin/sh
# prerm script for headscale.

set -e

# Summary of how this script can be called:
#        * <prerm> 'remove'
#        * <old-prerm> 'upgrade' <new-version>
#        * <new-prerm> 'failed-upgrade' <old-version>
#        * <conflictor's-prerm> 'remove' 'in-favour' <package> <new-version>
#        * <deconfigured's-prerm> 'deconfigure' 'in-favour'
#          <package-being-installed> <version> 'removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package.


case "$1" in
    remove)
      if [ -d /run/systemd/system ]; then
          deb-systemd-invoke stop headscale.service >/dev/null || true
      fi
    ;;
    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac
